[package]
name = "tessera-wasm"
description = "Tessera's signing policy for JavaScript, via wasm-bindgen."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tessera-policy.workspace = true
stellar-xdr.workspace = true
serde = { workspace = true }
serde_json.workspace = true
wasm-bindgen = "0.2"

[lints]
workspace = true
